<?php if ($this->pageCount): ?>
    <div class="pagination pagination-center">
        <div>
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <div class="pagination-block">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </div>
            <?php else: ?>
                <div class="pagination-block disabled">
                    <a href="#">
                        <<
                    </a>
                </div>
            <?php endif; ?>
             <!-- Numbered page divnks -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <div class="pagination-block">
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </div>
                <?php else: ?>
                    <div class="pagination-block active">
                        <a href="#"><?php echo $page; ?></a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
             <!-- Next page divnk -->
            <?php if (isset($this->next)): ?>
                <div class="pagination-block">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </div>
            <?php else: ?>
                <div class="pagination-block disabled">
                    <a href="#">
                        >>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>