<?php
$title = 'Add new car';
$this->headTitle($title);
?>
<h1>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<?php
$form->setAttribute('action', $this->url('car', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('brand'));
echo $this->formRow($form->get('model'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();