<?php
$title = 'My cars';
$this->headTitle($title);
?>
<h1>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<p>
	<a href="<?php echo $this->url('car', array('action'=>'add'));?>">Add new car</a>
</p>

<table class="table">
	<tr>
		<th>Brand</th>
		<th>Model</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($cars as $car) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($car->brand);?></td>
		<td><?php echo $this->escapeHtml($car->model);?></td>
		<td><a
			href="<?php echo $this->url('car', array('action'=>'edit', 'id' => $car->id));?>">Edit</a> <a
			href="<?php echo $this->url('car', array('action'=>'delete', 'id' => $car->id));?>">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
