<?php
$title = 'My cars';
$this->headTitle($title);
?>
<h1>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<p>
	<a href="<?php echo $this->url('car', array('action'=>'add'));?>">Add new car</a>
</p>

<table class="table">

	<?php
	// add at the end of the file after the table
	echo $this->paginationControl(
	    // the paginator object
	    $this->paginator,
	    // the scrolling style
	    'sliding',
	    // the partial to use to render the control
	    array('partial/paginator.phtml', 'Car'),
	    // the route to link to when a user clicks a control link
	    array(
	        'route' => 'car'
	    )
	); ?>
	<tr>
		<th>Brand</th>
		<th>Model</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($this->paginator as $car) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($car->getBrand());?></td>
		<td><?php echo $this->escapeHtml($car->getModel());?></td>
		<td><a
			href="<?php echo $this->url('car', array('action'=>'edit', 'id' => $car->id));?>">Edit</a> <a
			href="<?php echo $this->url('car', array('action'=>'delete', 'id' => $car->id));?>">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
