<?php
// module/Album/view/album/album/index.phtml:
$title = 'My albums';
$this->headTitle($title);
?>
<h1>
	<?php echo $this->escapeHtml($title); ?>
</h1>
<p>
	<a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add
		new album</a>
</p>

<table id="album-table" class="table">
	<?php
	// add at the end of the file after the table
	echo $this->paginationControl(
	    // the paginator object
	    $this->paginator,
	    // the scrolling style
	    'sliding',
	    // the partial to use to render the control
	    array('partial/paginator.phtml', 'Album'),
	    // the route to link to when a user clicks a control link
	    array(
	        'route' => 'album'
	    )
	); ?>
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>Action</th>
	</tr>
	<?php foreach ($this->paginator as $album) : ?>
	<tr id="rowid-<?php echo $album->id;?>">
		<td><?php echo $this->escapeHtml($album->title);?></td>
		<td><?php echo $this->escapeHtml($album->artist);?></td>
		<td>
			<a href="<?php echo $this->url('album', array('action'=>'edit', 'id' => $album->id));?>">Edit</a> 
			<a id="remove-<?php echo $album->id;?>" class="remove-link" href="#">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
	
	
</table>
