<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
 
if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}

?>

<h2>Non sei registrato? <a href="<?php echo $this->url('user', array('action' => 'index'));?>">Registrati!!!</a></h2>